spring:
  jpa:
    show-sql: true
    properties:
      hibername:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      encoding: utf-8
  h2:
    console:
      enabled: true

